server:
  port: 80

spring:
  activemq:
    broker-url: tcp://10.21.7.98/:61616
    user: admin
    password: ammin

    pool:
      enabled: true
      #连接池最大连接数
      max-connections: 5
      #空闲的连接过期时间，默认为30秒
      idle-timeout: 0
    packages:
      trust-all: true
  jms:
    pub-sub-domain: true